### ISSUE TITLE
NVIDIA Jetson Deployment

### ISSUE THREAD

**Issue by ZexinLi0w0** [IrohXu/lanenet-lane-detection-pytorch#22]
Thanks for sharing your code. This repo dependency seems to solve the deployment problem on NVIDIA Jetson embedded board based on arm64; the mainstream python environment is python=3.6+pytorch=1.8.0 (but the official Tusimple repo supports only python=3.8); we plan to deploy and test if your repo can be deployed on NVIDIA Jetson Nano / TX2 / AGX / Orin.  If there is any progress or issues, I will update you here to help you improve this repo.

**Comment by IrohXu** [comment]
Sounds good.
Thanks for your excellent idea. Please merge your branch to the main branch once your code works.

**Comment by ZexinLi0w0** [comment]
The performance under NVIDIA Jetson TX1 (512GFLOPS) should be 10-20 FPS reported in the [ENet](https://arxiv.org/pdf/1606.02147.pdf) paper. I deployed your code onto an NVIDIA Jetson Nano(472GFLOPS) and found the inference time per frame (excluding data transfer time and pre-processing time) is longer than 5 seconds (<0.2FPS). 

After profiling, I found that the latency is mainly concentrated in LaneNet.py at line 61 "c = self._encoder(input_tensor)". Are you sure that following the original implementation of ENet?

**Comment by ZexinLi0w0** [comment]
This is the test data on different terminals for reference.

<html xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=PowerPoint.Slide>
<meta name=Generator content="Microsoft PowerPoint 15">


</head>

<body>




  | Initialization | Preprocess | Data Transfer | Inference
-- | -- | -- | -- | --
Server GPU 2080 Ti | 3.27s | 0.060s | 0.0005s | 0.65s
AGX | 4.89s | 0.065s | 0.0019s | 2.39s
TX2 | 8.54s | 0.070s | 0.0049s | 3.68s
Nano | 13.69s | 0.178s | 0.0240s | 7.11s




</body>

</html>

**Comment by IrohXu** [comment]
hmm, this is weird. Though ENet is a self-defined code from me. I did not see any bottlenecks might influence the latency. Can you test the latency for U-Net?

**Comment by ZexinLi0w0** [comment]
> 

It's more likely a statistical error caused by a system-level internal problem (I guess it may be a memory issue). The runtime is calculated by only inference of one example. We modify the performance profiling code like below:

```
img = preprocess(img_path) 
begin = time.time()
for i in range(100):
  model(img)
end = time.time()
print("time elasped: {}".format(end - begin))
```

![image](https://user-images.githubusercontent.com/35922034/209204117-9da6b0ab-e294-440a-b840-ec7a75681087.png)

You can see the time of the first two inferences is significantly longer than others.

After moving the significant outliers, we profile the inference performance again on Nano, and the average performance reaches 4.0 FPS. (keep only binary decoder 4.7FPS and keep only instance decoder 4.7FPS).

**Comment by ZexinLi0w0** [comment]
To improve the real-time performance of your code, I have two suggestions: 
1. reducing the resolution of the input images.
2. use half-precision (FP16) or even INT8 inference instead of FP32. (inspired by YOLOv5)

Here are some hardware-independent (FLOPS) and hardware-dependent (FPS) performance data: 
ENet(LaneNet) (512x256) = 9.57 GFLOPS  -> 4.0FPS on Nano
ENet(LaneNet) (100x100) = 0.68 GFLOPS -> 7.9FPS on Nano
Object detection
yolov5l-cls (224x224) = 4.19 GFLOPS
yolov5n-cls (224x224) = 0.18 GFLOPS

**Comment by IrohXu** [comment]
It makes sense to me. I remember did not resize the input image in the dataloader. You can resize it to 480x360 or even smaller and retrain the model. 
Replace FP32 to FP16 or BF16 is a good trick. Need to test the performance after adding some APIs.
