### ISSUE TITLE
关于instance的输出结果

### ISSUE THREAD

**Issue by cvchanghao** [IrohXu/lanenet-lane-detection-pytorch#3]
你好，想求证个问题。
我看你的代码里，是将网络输出的3维特征，经过sigmoid之后，乘以255，来直接展示实例化结果的？ 所以某根车道线像素点的颜色并不完全一致？（例如，虽然看起来都是红色，但可能像素值有微小差别？）

**Comment by IrohXu** [comment]
会有差别，推荐在后处理阶段对实例化输出进行聚类，LaneNet原文也是类似的策略。后处理的代码我近期不会去做，会先做Focal Loss替换和修改网络架构，你可以自己研究一下。实例化输出3通道是为了可视化方便，可以修改为输出任意通道，最后在one-hot向量上聚类即可。

Iroh
