### ISSUE TITLE
Isn't there DBSCAN clustering algorithm here?

### ISSUE THREAD

**Issue by landkwon94** [IrohXu/lanenet-lane-detection-pytorch#6]
Hello Sir, I am now processing your nice code these days. and I have some question :)

I saw there was DBSCAN clustering algorithm in the original codes of LaneNet. However, it seems this pytorch code is not creating DBSCAN results when I try inference.. May I listen to your comments about this issue?

Many thanks!

**Comment by Berrlinn** [comment]
> Hello Sir, I am now processing your nice code these days. and I have some question :)
> 
> I saw there was DBSCAN clustering algorithm in the original codes of LaneNet. However, it seems this pytorch code is not creating DBSCAN results when I try inference.. May I listen to your comments about this issue?
> 
> Many thanks!

So, did you got the DBSCAN results?
I am facing the same issue, this code is only giving binary and instance output. 
Please help sir

**Comment by IrohXu** [comment]
Hi, landkwon94 and Berrlinn:

Here is the demo (https://github.com/Turoad/lanedet) that may be helpful for adding clustering algo and solve post-processing problem. I am busy with my job in these days, so do not have enough time to update the code. If you like, you can refer to this github repo. I will add the DBSCAN with Tusimple format later.

https://github.com/Turoad/lanedet
